'use client'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
//import Alert from "@/components/common/alert";
import { ReactQueryProvider } from "./react-query-provider";
//import { ContentLayout } from "@/components/admin-panel/content-layout";
//import DialogModal from "@/components/common/dialog";
import { TooltipProvider } from "@/components/ui/tooltip";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ConfirmDialogProvider } from "@omit/react-confirm-dialog";

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <ReactQueryProvider>
      <NuqsAdapter>
        <ConfirmDialogProvider>
          <TooltipProvider>
            <html lang="en">
              <body>
                {children}
                <Toaster />
                {/*<Alert />
                <DialogModal />*/}
              </body>
            </html>
          </TooltipProvider>
        </ConfirmDialogProvider>
      </NuqsAdapter>
    </ReactQueryProvider>
  );
}
